spring:
  application:
    name: sb-server
  datasource:
    url: jdbc:postgresql://localhost:5432/item
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

